services:
  # test_db:
  #   image: postgres:17
  #   environment:
  #     POSTGRES_PASSWORD: testpassword
  #     POSTGRES_USER: testuser
  #     POSTGRES_DB: portfolio_test
  #   ports:
  #     - "5555:5432" # why 5555?
  #   healthcheck:
  #     test: [ "CMD-SHELL", "pg_isready -U testuser -d portfolio_test" ]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  test_backend:
    build:
      context: ./api
    environment:
      APP_ENV: testing
      APP_DEBUG: "true"
      APP_KEY: base64:6GnHZ3+/NKRRPp7HQrh8HquZwoDKS9t00YfbMegXX2U=

      DB_CONNECTION: pgsql
#      INSTANCE_UNIX_SOCKET: test_db
      DB_URL: postgresql://neondb_owner:npg_0VnOFkoU3bxD@ep-quiet-frost-a9txwvv1.gwc.azure.neon.tech/neondb?sslmode=require&channel_binding=require
      # DB_PORT: 5432
      # DB_NAME: portfolio_test
      # DB_USER: testuser
      # DB_PASS: testpassword

      CACHE_STORE: array
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: array
    command: >
      bash -c "php artisan config:clear &&
               php artisan migrate:fresh --force &&
               php artisan db:seed --force &&
               /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf"
    ports:
      - "8000:80"
    #depends_on:
      # test_db:
      #   condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - test_backend

networks:
  default:
    name: app-network
