<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TodoController;



// Autogenerated. Left here for reference.
Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');

Route::prefix('notepads')->group(function () {
    // Get and create todos for a notepad
    Route::get('/{notepad}/todos', [TodoController::class, 'getAllTodos']);
    Route::post('/{notepad}/todos', [TodoController::class, 'store']);
    Route::put('/{notepad}/todo-order', [TodoController::class, 'moveTodo']);
});

Route::prefix('todos')->group(function () {
    // Todo operations
    Route::delete('/{id}', [TodoController::class, 'destroy']);
    Route::put('/{id}', [TodoController::class, 'update']);
    Route::patch('/{id}/status', [TodoController::class, 'toggleStatus']);
});
